### ISSUE TITLE
Add support for SQL server

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-app-db#3]
Ref. https://github.com/uhppoted/uhppoted-app-db/issues/2

Go driver: https://github.com/denisenkom/go-mssqldb
Superseded by: https://github.com/microsoft/go-mssqldb

**Comment by twystd** [comment]
- [ ] get-acl
- [ ] put-acl
- [ ] compare-acl
- [ ] load-acl
- [ ] store-acl
- [ ] README
- [ ] CHANGELOG

**Comment by twystd** [comment]
Provisional implementation of SQL Server support - pending release v0.8.6
