### ISSUE TITLE
Add bindings for Postgres

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-app-db#6]
Tasks:
- [x] get-acl
- [x] put-acl
- [x] compare-acl
- [x] load-acl
- [x] store-acl
- [x] get-events
- [x] CHANGELOG
- [x] README

Notes:
1. https://github.com/jackc/pgx
2. https://henvic.dev/posts/go-postgres/

**Comment by twystd** [comment]
Feature complete, pending release v0.8.7
